### PR TITLE
[submodule] updates and other fixes

### PR DESCRIPTION
**Pull request by edmont**
Depends on:

- [x] https://github.com/openthread/openthread/pull/7419

### CODE REVIEW

**Comment by simonlingoogle** [comment]
Seems we don't have any CI tests. 

Wondering what kind of tests do we need? @edmont @superwhd 

Not sure if it's possible to build reference releases in GitHub CI.

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Comment by edmont** [comment]
Actually just realized that would be better to merge https://github.com/openthread/openthread/pull/7419 first and then update `openthread` submodule here.

**Comment by edmont** [comment]
> Seems we don't have any CI tests.
> 
> Wondering what kind of tests do we need? @edmont @superwhd
> 
> Not sure if it's possible to build reference releases in GitHub CI.

There are a few possible build combinations:

- REFERENCE_PLATFORM=(nrf52840|efr32mg12|ncs)
- REFERENCE_RELEASE_TYPE=(certification|1.3)

As we don't have a simulation platform I'd say it'd be difficult to run some tests. We could have some build tests, but notice `ncs` is quite space and bandwidth demanding.

**Comment by edmont** [comment]
I took the liberty to include `ot-commissioner` update in this PR as well. @jwhui feel free to squash commits if needed.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
