### PR TITLE
Update NCS and submodules

### PR DESCRIPTION
**Pull request by maciejbaczmanski**
Updating NCS to `4d1c577ef2cadc7f9270c575ec3808cf892c9f34`

Updating submodules to:

- openthread: 8bc25042ba5cde20605eec2a329c0dff575303f4
- ot-br-posix: 790dc775144e33995cd1cb2c15b348849cacf737
- ot-nrf528xx: 982244f4bad13c1137bf9c4065b8948b35ff6d6c
- ot-commisioner: acb3371f6c5eb2c9b1f7fbaf34c5d8f49378871e

### CODE REVIEW

**Comment by maciejbaczmanski** [comment]
@jwhui could you run CI on this PR? It's my first contribution to this repository

**Comment by wgtdkp** [comment]
> @jwhui could you run CI on this PR? It's my first contribution to this repository

CI triggered!

**Comment by maciejbaczmanski** [comment]
@wgtdkp I don't have full access to CI's logs, but I can see that there was some error:
System.IO.IOException: No space left on device : '/home/runner/runners/2.305.0/_diag/Worker_20230711-092010-utc.log'
I've build reference release 1.3 on my computer and it passed correctly. I can see that this check has been failing with similar error code in few previous builds.

**Comment by sunytt** [comment]
> @wgtdkp I don't have full access to CI's logs, but I can see that there was some error: System.IO.IOException: No space left on device : '/home/runner/runners/2.305.0/_diag/Worker_20230711-092010-utc.log' I've build reference release 1.3 on my computer and it passed correctly. I can see that this check has been failing with similar error code in few previous builds.

@maciejbaczmanski FYI, the build machine run out of space, this pr https://github.com/openthread/ot-reference-release/pull/63 should be able to solve it.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
