### PR TITLE
bump version of NCS and openthread stack

### PR DESCRIPTION
**Pull request by canisLupus1313**
This PR bumps versions of openthread stack and ncs

### CODE REVIEW

**Review by suveshpratapa — CHANGES_REQUESTED** [review]
@canisLupus1313 Also require an update to "openthread" submodule? @ `615e951`

**Comment by canisLupus1313** [comment]
@suveshpratapa good catch. Already fixed.

**Review by suveshpratapa — CHANGES_REQUESTED** [review]
I have one more request.

Can we wait until https://github.com/openthread/ot-br-posix/pull/1544 is merged?  Then we can update the openthread commit to be at: `13df037`... there are a couple of new commits in the repo from yesterday that we want to use.

**Comment by suveshpratapa** [comment]
@canisLupus1313 https://github.com/openthread/ot-br-posix/pull/1544 is merged.

So we can now update:
openthread @ `13df037`
ot-br-posix @ `18ecb2f`

**Review by suveshpratapa — CHANGES_REQUESTED** [review]
@canisLupus1313 https://github.com/openthread/ot-br-posix/pull/1544 is merged.

So we can now update:
openthread @ 13df037
ot-br-posix @ 18ecb2f

**Review by suveshpratapa — APPROVED** [review]
LGTM

**Review by suveshpratapa — APPROVED** [review]
LGTM

**Comment by edmont** [comment]
Hi @canisLupus1313 @suveshpratapa, should we update the PR with the latest added THCI fixes?

- https://github.com/openthread/openthread/pull/8235
- https://github.com/openthread/ot-commissioner/pull/232
- https://github.com/openthread/openthread/pull/8261

**Comment by jwhui** [comment]
> Hi @canisLupus1313 @suveshpratapa, should we update the PR with the latest added THCI fixes?
> 
> * [[thci] remove unneeded problematic command openthread#8235](https://github.com/openthread/openthread/pull/8235)
> * [[thci] change python format string to format function ot-commissioner#232](https://github.com/openthread/ot-commissioner/pull/232)
> * [[thci] fix `setBbrDataset` openthread#8261](https://github.com/openthread/openthread/pull/8261)

@canisLupus1313 , any thoughts on this?

**Comment by canisLupus1313** [comment]
@jwhui 
I have already uploaded the generated reference device for Tom with the fixed for THCI. 

But we can align it to a newer openthread for consistency in separate PR (to keep those changes in history).
@suveshpratapa any thoughts?

**Comment by suveshpratapa** [comment]
> @jwhui 
> 
> I have already uploaded the generated reference device for Tom with the fixed for THCI. 
> 
> 
> 
> But we can align it to a newer openthread for consistency in separate PR (to keep those changes in history).
> 
> @suveshpratapa any thoughts?

This sounds like a good idea. We can have this point as a snapshot, since we also produced reference device images at that commit.

**Comment by jwhui** [comment]
> This sounds like a good idea. We can have this point as a snapshot, since we also produced reference device images at that commit.

@canisLupus1313 @suveshpratapa , thanks for the update. So we should go ahead and merge this PR?

**Comment by suveshpratapa** [comment]
> > This sounds like a good idea. We can have this point as a snapshot, since we also produced reference device images at that commit.
> 
> 
> 
> @canisLupus1313 @suveshpratapa , thanks for the update. So we should go ahead and merge this PR?

Sounds good to me, let's do it -- I already approved it so good from my end.

(Sorry for not being prompt, I'm on vacation.)

**Review by jwhui — APPROVED** [review]

**Pull request merged**
