### PR TITLE
Synchronize the openthread, ot-br-posix and ot-nrf528xx to the latest version

### PR DESCRIPTION
**Pull request by zhanglongxia**
Update openthread to 0fc8ce95eaedbfa130c547e82b5f8275655cbdc2. 
Update ot-br-posix to d15b080045e96f5515cab7badad3575fa38615a2.
Update ot-nrf528xx to e801931e10bbb76d5a095921c5861bf1a3830561.

### CODE REVIEW

**Comment by superwhd** [comment]
I wonder if you've verified building a release using the latest commits? @zhanglongxia 

Also, I wonder if we should add git tags on the HEAD before making big submodule updates and they can be regarded as relative 'stable' releases.

**Comment by zhanglongxia** [comment]
>

**Comment by zhanglongxia** [comment]
> I wonder if you've verified building a release using the latest commits? @zhanglongxia
> 
> Also, I wonder if we should add git tags on the HEAD before making big submodule updates and they can be regarded as relative 'stable' releases.

I have verified the latest commits using the command `REFERENCE_PLATFORM=nrf52840 REFERENCE_RELEASE_TYPE=1.3 OTBR_RCP_BUS=UART IN_CHINA=1 ./script/make-reference-release.bash`. 

I don't know if we should add git tags on the HEAD. @librasungirl Could you provide some suggestions?

**Comment by superwhd** [comment]
Hi @zhanglongxia, shall we close this PR since the submodules have been already updated?

**Pull request closed without merging**
