### PR TITLE
Update ot-commissioner to latest for 1.4 reference builds

### PR DESCRIPTION
**Pull request by suveshpratapa**

### CODE REVIEW

**Review by superwhd — APPROVED** [review]
LGTM 👍

**Comment by superwhd** [comment]
Please also update the changelog. Thanks!

**Review by jwhui — APPROVED** [review]

**Comment by jwhui** [comment]
> @jwhui Can we please get this PR merged? Thank you.

@suveshpratapa , can you help resolve conflicts?

**Comment by librasungirl** [comment]
Suggest to update to the hash with https://github.com/openthread/ot-commissioner/pull/292 , ( nice to have https://github.com/openthread/ot-commissioner/pull/293 which is close to merge), which supports secure session establishment without petition to meet ePSKc test plan's requirement

**Comment by librasungirl** [comment]
> Suggest to update to the hash with [openthread/ot-commissioner#292](https://github.com/openthread/ot-commissioner/pull/292) already merged, ( nice to have [openthread/ot-commissioner#293](https://github.com/openthread/ot-commissioner/pull/293) which is close to merge), which supports secure session establishment without petition to meet ePSKc test plan's requirement

and maybe in this or separate PR, OpenThread repo needs update to have the mandatory changes https://github.com/openthread/openthread/pull/10524 for cert requirements

**Comment by librasungirl** [comment]
> Suggest to update to the hash with [openthread/ot-commissioner#292](https://github.com/openthread/ot-commissioner/pull/292) already merged, ( nice to have [openthread/ot-commissioner#293](https://github.com/openthread/ot-commissioner/pull/293) which is close to merge), which supports secure session establishment without petition to meet ePSKc test plan's requirement

may update to `639e627` which has the updated/new cli commands for epskc test @suveshpratapa

**Review by jwhui — APPROVED** [review]

**Pull request merged**
