### PR TITLE
enable `BORDER_ROUTING`

### PR DESCRIPTION
**Pull request by edmont**
Build certification reference border router with BORDER_ROUTING enabled. This is required for MATN-TC-02 for TD roles.

### CODE REVIEW

**Comment by edmont** [comment]
See discussion in https://github.com/openthread/openthread/issues/7175

**Comment by simonlingoogle** [comment]
I doubt if we need BORDER ROUTING for Thead 1.2 certification reference BR. 
Seems too much complexity added.

**Comment by edmont** [comment]
I don't think `OT_ICMP6_ECHO_HANDLER_ALL` is the best solution for final products (actually it can't be currently configured) so my approach is to build the reference device as similar as possible as the final product. Your concern is just a matter of reference device resources?

**Comment by simonlingoogle** [comment]
> I don't think `OT_ICMP6_ECHO_HANDLER_ALL` is the best solution for final products (actually it can't be currently configured) so my approach is to build the reference device as similar as possible as the final product. Your concern is just a matter of reference device resources?

BORDER_ROUTING adds too much logic to the reference devices? For example, BORDER_ROUTING will automatically add OMR prefix to the Network Data. BORDER_ROUTING will also automatically add external routes to Network Data for any prefixes it discovered from the Backbone link. I am concerned these behavior may interference with the normal certification process. 

It's better to keep the reference device's behavior as simple as possible. 

Thoughts?

**Comment by edmont** [comment]
I agree it adds extra complexity, my main point is this complexity may uncover Thread Harness issues that would occur when using regular Thread devices built with `BORDER_ROUTING` support as DUT. But okay, lets address those when the time comes. 

Please check https://github.com/openthread/openthread/pull/7288

**Pull request closed without merging**
